name: noname
description: A new Flutter project.
publish_to: 'none' # Remove this line if publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.1
  crypto: ^3.0.3
  image_picker: ^1.0.4
  # Версия 17.0.0+ решает проблему "ambiguous reference" на новых Android SDK
  flutter_local_notifications: ^17.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
